window.WORDS = {
  "faciles": {
    "comida": [
      "pizza",
      "manzana",
      "hamburguesa",
      "pera",
      "platano",
      "naranja",
      "uva",
      "sandia",
      "melon",
      "fresa",
      "cereza",
      "limon",
      "lima",
      "mango",
      "papaya",
      "kiwi",
      "durazno",
      "albaricoque",
      "ciruela",
      "granada",
      "tomate",
      "lechuga",
      "zanahoria",
      "pepino",
      "cebolla",
      "ajo",
      "patata",
      "arroz",
      "pasta",
      "pan",
      "queso",
      "leche",
      "yogur",
      "huevo",
      "jamon",
      "pollo",
      "pescado",
      "atun",
      "salchicha",
      "sopa",
      "ensalada",
      "empanada",
      "tacos",
      "burrito",
      "arepa",
      "sushi",
      "lasana",
      "croqueta",
      "helado",
      "galleta",
      "chocolate"
    ],
    "animales": [
      "perro",
      "gato",
      "elefante",
      "leon",
      "tigre",
      "jirafa",
      "cebra",
      "mono",
      "gorila",
      "hipopotamo",
      "rinoceronte",
      "cocodrilo",
      "tortuga",
      "serpiente",
      "lagarto",
      "conejo",
      "hamster",
      "raton",
      "ardilla",
      "oso",
      "lobo",
      "zorro",
      "caballo",
      "vaca",
      "cerdo",
      "oveja",
      "cabra",
      "gallina",
      "gallo",
      "pato",
      "ganso",
      "pavo",
      "pez",
      "tiburon",
      "delfin",
      "ballena",
      "pulpo",
      "cangrejo",
      "camarones",
      "mariposa",
      "abeja",
      "hormiga",
      "escarabajo",
      "pajaro",
      "loro",
      "aguila",
      "buho",
      "paloma",
      "pinguino",
      "flamenco"
    ],
    "objetos_casa": [
      "sofa",
      "mesa",
      "silla",
      "lampara",
      "nevera",
      "horno",
      "microondas",
      "tostadora",
      "cafetera",
      "hervidor",
      "cuchillo",
      "tenedor",
      "cuchara",
      "plato",
      "vaso",
      "taza",
      "mantel",
      "cortina",
      "espejo",
      "alfombra",
      "cama",
      "almohada",
      "sabana",
      "colchon",
      "armario",
      "comoda",
      "estanteria",
      "escritorio",
      "televisor",
      "mando",
      "reloj",
      "cuadro",
      "florero",
      "escoba",
      "recogedor",
      "aspiradora",
      "plancha",
      "lavadora",
      "secadora",
      "detergente",
      "jabon",
      "toalla",
      "papel higienico",
      "cepillo",
      "pasta dental",
      "ducha",
      "grifo",
      "lavabo",
      "inodoro",
      "ventilador"
    ],
    "transporte": [
      "coche",
      "auto",
      "autobus",
      "micro",
      "camion",
      "camioneta",
      "moto",
      "bicicleta",
      "patinete",
      "tren",
      "tranvia",
      "metro",
      "taxi",
      "avion",
      "helicoptero",
      "barco",
      "velero",
      "yate",
      "crucero",
      "submarino",
      "lancha",
      "canoa",
      "kayak",
      "patin",
      "monopatin",
      "globo",
      "dirigible",
      "cohete",
      "nave",
      "tractor",
      "ambulancia",
      "bomberos",
      "camion cisterna",
      "furgon",
      "remolque",
      "grua",
      "teleferico",
      "funicular",
      "carruaje",
      "carreta",
      "segway",
      "moto acuatica",
      "triciclo",
      "bici electrica",
      "tren bala",
      "tren carga",
      "bus escolar",
      "bicitaxi",
      "caravana",
      "hoverboard"
    ],
    "ropa": [
      "camiseta",
      "pantalones",
      "vaqueros",
      "shorts",
      "falda",
      "vestido",
      "abrigo",
      "chaqueta",
      "sueter",
      "sudadera",
      "camisa",
      "blusa",
      "calcetines",
      "medias",
      "zapatos",
      "zapatillas",
      "botas",
      "sandalias",
      "gorra",
      "sombrero",
      "bufanda",
      "guantes",
      "cinturon",
      "corbata",
      "pajarita",
      "chaqueton",
      "impermeable",
      "pijama",
      "bata",
      "ropa interior",
      "sujetador",
      "boxer",
      "biquini",
      "bikini",
      "banador",
      "traje",
      "uniforme",
      "chaleco",
      "peto",
      "overol",
      "leggins",
      "mallas",
      "panuelo",
      "diadema",
      "pasamontanas",
      "chubasquero",
      "capa",
      "poncho",
      "bata bano",
      "camiseta tirantes"
    ],
    "lugares_comunes": [
      "colegio",
      "escuela",
      "instituto",
      "universidad",
      "hospital",
      "clinica",
      "parque",
      "plaza",
      "biblioteca",
      "supermercado",
      "mercado",
      "tienda",
      "farmacia",
      "banco",
      "oficina",
      "casa",
      "piso",
      "apartamento",
      "barrio",
      "estacion",
      "aeropuerto",
      "cine",
      "teatro",
      "museo",
      "restaurante",
      "cafeteria",
      "bar",
      "gimnasio",
      "piscina",
      "estadio",
      "iglesia",
      "ayuntamiento",
      "comisaria",
      "bomberos",
      "hotel",
      "gasolinera",
      "playa",
      "montana",
      "bosque",
      "carretera",
      "puente",
      "rio",
      "lago",
      "puerto",
      "puerto deportivo",
      "estadio cubierto",
      "polideportivo",
      "guarderia",
      "centro comercial",
      "centro salud"
    ],
    "colores": [
      "rojo",
      "azul",
      "amarillo",
      "verde",
      "naranja",
      "morado",
      "violeta",
      "rosa",
      "negro",
      "blanco",
      "gris",
      "marron",
      "beis",
      "turquesa",
      "cian",
      "magenta",
      "fucsia",
      "lima",
      "oliva",
      "coral",
      "mostaza",
      "ocre",
      "beige",
      "lavanda",
      "teal",
      "esmeralda",
      "rubi",
      "zafiro",
      "oro",
      "plata",
      "cobre",
      "bronce",
      "terracota",
      "salmon",
      "cereza",
      "pastel",
      "crema",
      "perla",
      "antracita",
      "grafito",
      "hielo",
      "marfil",
      "arena",
      "melon",
      "agua",
      "carbon",
      "ambar",
      "celeste",
      "pistacho",
      "berenjena",
      "gris claro"
    ],
    "deportes": [
      "futbol",
      "baloncesto",
      "tenis",
      "padel",
      "voleibol",
      "beisbol",
      "futbol americano",
      "rugby",
      "golf",
      "hockey",
      "hockey hielo",
      "natacion",
      "atletismo",
      "ciclismo",
      "boxeo",
      "artes marciales",
      "judo",
      "karate",
      "taekwondo",
      "esgrima",
      "gimnasia",
      "gimnasia ritmica",
      "patinaje",
      "patinaje artistico",
      "surf",
      "windsurf",
      "kitesurf",
      "vela",
      "remo",
      "canotaje",
      "escalada",
      "alpinismo",
      "senderismo",
      "esqui",
      "snowboard",
      "ping pong",
      "tenis mesa",
      "badminton",
      "squash",
      "balonmano",
      "waterpolo",
      "triatlon",
      "pentatlon",
      "dardos",
      "tiro con arco",
      "halterofilia",
      "automovilismo",
      "motociclismo",
      "curling",
      "lacrosse"
    ],
    "juguetes_juegos": [
      "pelota",
      "pelota playa",
      "canicas",
      "cometa",
      "avion papel",
      "puzzle",
      "rompecabezas",
      "lego",
      "bloques",
      "muneca",
      "muneco",
      "peluche",
      "coche juguete",
      "tren juguete",
      "robot",
      "dinosaurio juguete",
      "casita",
      "cocina juguete",
      "set medico",
      "plastilina",
      "slinky",
      "yoyo",
      "trompo",
      "peonza",
      "cartas",
      "loteria",
      "domino",
      "ajedrez",
      "damas",
      "oca",
      "parcheesi",
      "monopoly",
      "jenga",
      "videojuegos",
      "consola",
      "tablet juego",
      "tablero",
      "pista carreras",
      "cubo rubik",
      "patines",
      "bici sin pedales",
      "burbujas",
      "marioneta",
      "titere",
      "pistola agua",
      "palo golf juguete",
      "set pintura",
      "diabolo",
      "cuerda saltar",
      "pistola dardos"
    ]
  },
  "medias": {
    "profesiones": [
      "medico",
      "enfermero",
      "dentista",
      "veterinario",
      "profesor",
      "maestro",
      "ingeniero",
      "arquitecto",
      "abogado",
      "juez",
      "policia",
      "bombero",
      "piloto",
      "azafata",
      "cocinero",
      "camarero",
      "barista",
      "panadero",
      "carnicero",
      "pescadero",
      "agricultor",
      "jardinero",
      "mecanico",
      "electricista",
      "fontanero",
      "carpintero",
      "pintor",
      "peluquero",
      "maquillador",
      "disennador",
      "programador",
      "analista",
      "contable",
      "banquero",
      "vendedor",
      "comercial",
      "gerente",
      "empresario",
      "periodista",
      "fotografo",
      "actor",
      "actriz",
      "cantante",
      "musico",
      "repartidor",
      "taxista",
      "conductor",
      "camionero",
      "bibliotecario",
      "traductor"
    ],
    "peliculas_famosas": [
      "el padrino",
      "titanic",
      "avatar",
      "star wars",
      "el senor de los anillos",
      "harry potter",
      "matrix",
      "jurassic park",
      "indiana jones",
      "back to the future",
      "forrest gump",
      "toy story",
      "el rey leon",
      "la sirena",
      "aladdin",
      "frozen",
      "coco",
      "up",
      "shrek",
      "busqueda implacable",
      "gladiator",
      "braveheart",
      "inception",
      "interstellar",
      "the dark knight",
      "batman begins",
      "spiderman",
      "iron man",
      "avengers",
      "guardians of the galaxy",
      "black panther",
      "mad max fury road",
      "la la land",
      "whiplash",
      "parasite",
      "ciudad de dios",
      "el laberinto del fauno",
      "pulp fiction",
      "fight club",
      "se7en",
      "get out",
      "el gran lebowski",
      "rocky",
      "rambo",
      "terminator",
      "alien",
      "blade runner",
      "jaws",
      "back to the future 2",
      "el padrino 2"
    ],
    "instrumentos_musicales": [
      "guitarra",
      "bajo",
      "violin",
      "viola",
      "cello",
      "contrabajo",
      "piano",
      "teclado",
      "bateria",
      "tambor",
      "bongos",
      "congas",
      "timbales",
      "maracas",
      "triangulo",
      "flauta",
      "flauta dulce",
      "clarinete",
      "oboe",
      "fagot",
      "trompeta",
      "trombon",
      "tuba",
      "saxofon",
      "arpa",
      "acordeon",
      "bandoneon",
      "ukulele",
      "banjo",
      "mandolina",
      "sitar",
      "lira",
      "cimbalo",
      "organo",
      "sintetizador",
      "kazoo",
      "armonica",
      "castanuelas",
      "xilofono",
      "vibrafono",
      "metalofono",
      "pandereta",
      "clave",
      "guiro",
      "cuica",
      "dulzaina",
      "gaita",
      "didgeridoo",
      "kalimba",
      "ocarina"
    ],
    "paises_ciudades": [
      "espana",
      "portugal",
      "francia",
      "italia",
      "alemania",
      "reino unido",
      "irlanda",
      "escocia",
      "gales",
      "suiza",
      "belgica",
      "holanda",
      "suecia",
      "noruega",
      "finlandia",
      "dinamarca",
      "islandia",
      "polonia",
      "grecia",
      "turquia",
      "rusia",
      "china",
      "japon",
      "corea",
      "india",
      "pakistan",
      "australia",
      "nueva zelanda",
      "estados unidos",
      "canada",
      "mexico",
      "brasil",
      "argentina",
      "chile",
      "peru",
      "colombia",
      "venezuela",
      "ecuador",
      "bolivia",
      "paraguay",
      "uruguay",
      "cuba",
      "republica dominicana",
      "panama",
      "costa rica",
      "guatemala",
      "honduras",
      "nicaragua",
      "el salvador",
      "marruecos"
    ],
    "tecnologia": [
      "smartphone",
      "tablet",
      "laptop",
      "pc",
      "smartwatch",
      "auriculares",
      "altavoz bluetooth",
      "camara",
      "dron",
      "consola",
      "videojuego",
      "router",
      "modem",
      "wifi",
      "bluetooth",
      "usb",
      "disco duro",
      "ssd",
      "nube",
      "app",
      "navegador",
      "buscador",
      "correo",
      "mensaje",
      "chat",
      "red social",
      "streaming",
      "podcast",
      "gps",
      "mapa",
      "asistente virtual",
      "inteligencia artificial",
      "robot",
      "impresora",
      "escaner",
      "teclado",
      "raton",
      "monitor",
      "proyector",
      "realidad virtual",
      "realidad aumentada",
      "microfono",
      "webcam",
      "cargador",
      "powerbank",
      "smart tv",
      "domotica",
      "sensor",
      "wearable",
      "codigo qr"
    ],
    "fiestas_celebraciones": [
      "cumpleanos",
      "navidad",
      "ano nuevo",
      "reyes",
      "pascua",
      "halloween",
      "carnaval",
      "san valentin",
      "san juan",
      "dia del nino",
      "dia del padre",
      "dia de la madre",
      "boda",
      "bautizo",
      "comunion",
      "graduacion",
      "aniversario",
      "despedida soltero",
      "baby shower",
      "fiesta sorpresa",
      "inauguracion",
      "festival",
      "feria",
      "romeria",
      "fiesta patronal",
      "nochevieja",
      "fin de curso",
      "barbacoa",
      "picnic",
      "pijamada",
      "reunion familiar",
      "despedida",
      "bienvenida",
      "fiesta pool",
      "fiesta playa",
      "fiesta disfraces",
      "fiesta tematica",
      "fiesta infantil",
      "fiesta casera",
      "verbena",
      "festival musica",
      "concierto",
      "primera comunion",
      "quinceanos",
      "carnaval brasil",
      "hanukkah",
      "ramadan",
      "eid",
      "thanksgiving",
      "fiesta hawaiana"
    ],
    "vacaciones": [
      "playa",
      "montana",
      "camping",
      "hotel",
      "hostal",
      "crucero",
      "resort",
      "spa",
      "balneario",
      "excursion",
      "ruta",
      "roadtrip",
      "mochilero",
      "viaje",
      "turismo",
      "paseo",
      "visita guiada",
      "parque tematico",
      "museo",
      "ciudad",
      "pueblo",
      "isla",
      "lago",
      "rio",
      "bosque",
      "safari",
      "aventura",
      "esqui",
      "snowboard",
      "buceo",
      "snorkel",
      "surf",
      "vacaciones invierno",
      "vacaciones verano",
      "vacaciones familia",
      "puente",
      "fin de semana",
      "escapada",
      "fotografia",
      "alquiler coche",
      "maleta",
      "pasaporte",
      "visado",
      "mapa",
      "itinerario",
      "aeropuerto",
      "estacion",
      "souvenirs",
      "senderismo",
      "visitar familia"
    ],
    "tiendas_marcas": [
      "supermercado",
      "hipermercado",
      "tienda barrio",
      "farmacia",
      "panaderia",
      "pasteleria",
      "carniceria",
      "pescaderia",
      "fruteria",
      "ferreteria",
      "papeleria",
      "libreria",
      "zapateria",
      "perfumeria",
      "joyeria",
      "relojeria",
      "optica",
      "gasolinera",
      "mercado",
      "tienda ropa",
      "tienda deportes",
      "tienda juguetes",
      "tienda tecnologia",
      "electronica",
      "tienda muebles",
      "outlet",
      "bazar",
      "quiosco",
      "floristeria",
      "estanco",
      "tienda regalos",
      "tienda mascotas",
      "tienda bicis",
      "tienda fotografia",
      "tienda alimentacion",
      "tienda delicatessen",
      "tienda ecologica",
      "tienda segunda mano",
      "tienda online",
      "amazon",
      "ikea",
      "zara",
      "nike",
      "adidas",
      "apple",
      "google",
      "microsoft",
      "samsung",
      "carrefour",
      "walmart"
    ],
    "postres_dulces": [
      "helado",
      "tarta",
      "pastel",
      "bizcocho",
      "cupcake",
      "muffin",
      "brownie",
      "galleta",
      "bombon",
      "chocolate",
      "caramelo",
      "flan",
      "natilla",
      "arroz con leche",
      "churros",
      "bunuelos",
      "donut",
      "rosquilla",
      "croissant",
      "milhojas",
      "tiramisu",
      "panna cotta",
      "gelatina",
      "mousse",
      "sorbete",
      "yogurt",
      "fresas con nata",
      "crema catalana",
      "tocino cielo",
      "natillas",
      "alfajor",
      "polvoron",
      "mazapan",
      "torrija",
      "roscon",
      "merengue",
      "trufa",
      "bombon licor",
      "mermelada",
      "miel",
      "gofre",
      "waffle",
      "paleta",
      "malvavisco",
      "chicle",
      "piruleta",
      "algodon azucar",
      "cheesecake",
      "crepe",
      "barquillo"
    ]
  },
  "dificiles": {
    "conceptos_abstractos": [
      "libertad",
      "justicia",
      "igualdad",
      "amor",
      "odio",
      "felicidad",
      "tristeza",
      "exito",
      "fracaso",
      "tiempo",
      "eternidad",
      "destino",
      "suerte",
      "poder",
      "paz",
      "guerra",
      "verdad",
      "mentira",
      "fe",
      "esperanza",
      "miedo",
      "ansiedad",
      "estres",
      "creatividad",
      "belleza",
      "sentido",
      "proposito",
      "identidad",
      "memoria",
      "conciencia",
      "empatia",
      "orgullo",
      "humildad",
      "ambicion",
      "moral",
      "etica",
      "responsabilidad",
      "respeto",
      "honor",
      "lealtad",
      "paciencia",
      "resiliencia",
      "nostalgia",
      "soledad",
      "confianza",
      "compromiso",
      "cambio",
      "orden",
      "caos",
      "silencio"
    ],
    "emociones": [
      "alegria",
      "tristeza",
      "miedo",
      "ira",
      "asco",
      "sorpresa",
      "ansiedad",
      "nervios",
      "calma",
      "serenidad",
      "orgullo",
      "verguenza",
      "culpa",
      "envidia",
      "celos",
      "gratitud",
      "entusiasmo",
      "aburrimiento",
      "frustracion",
      "nostalgia",
      "esperanza",
      "desesperacion",
      "empatia",
      "compasion",
      "melancolia",
      "euforia",
      "alivio",
      "ternura",
      "confusion",
      "timidez",
      "admiracion",
      "indiferencia",
      "decepcion",
      "desilusion",
      "panico",
      "resentimiento",
      "rencor",
      "inseguridad",
      "satisfaccion",
      "irritacion",
      "vergonzoso",
      "carino",
      "apego",
      "desagrado",
      "asombro",
      "felicidad",
      "angustia",
      "tension",
      "desamparo",
      "ilusion"
    ],
    "epocas_historicas": [
      "prehistoria",
      "paleolitico",
      "neolitico",
      "edad antigua",
      "edad media",
      "edad moderna",
      "edad contemporanea",
      "imperio romano",
      "grecia clasica",
      "egipto antiguo",
      "mesopotamia",
      "edad bronce",
      "edad hierro",
      "renacimiento",
      "barroco",
      "ilustracion",
      "revolucion industrial",
      "revolucion francesa",
      "edad victoriana",
      "guerra fria",
      "primera guerra mundial",
      "segunda guerra mundial",
      "colonizacion",
      "edad dorada",
      "edad del hielo",
      "edad piedra",
      "feudalismo",
      "cruzadas",
      "reforma",
      "contrarreforma",
      "descubrimiento america",
      "siglo xix",
      "siglo xx",
      "siglo xxi",
      "modernismo",
      "realismo",
      "romanticismo",
      "impresionismo",
      "modernidad",
      "contemporaneidad",
      "posguerra",
      "antigua china",
      "edad oscura",
      "belle epoque",
      "anos 20",
      "anos 60",
      "edad de oro espana",
      "revolucion rusa",
      "guerra civil",
      "antiguedad clasica"
    ],
    "libros_literatura": [
      "don quijote",
      "cien anos soledad",
      "la odisea",
      "la iliada",
      "romeo y julieta",
      "hamlet",
      "macbeth",
      "el principito",
      "el alquimista",
      "orgullo y prejuicio",
      "sherlock holmes",
      "dracula",
      "frankenstein",
      "moby dick",
      "guerra y paz",
      "crimen y castigo",
      "los miserables",
      "el conde de montecristo",
      "duna",
      "1984",
      "rebelion granja",
      "fahrenheit 451",
      "el hobbit",
      "el senor de los anillos",
      "harry potter",
      "los juegos del hambre",
      "crepusculo",
      "ana karenina",
      "el nombre de la rosa",
      "la divina comedia",
      "el paraiso perdido",
      "la metamorfosis",
      "el proceso",
      "rayuela",
      "el tunel",
      "la casa de los espiritus",
      "el amor en los tiempos del colera",
      "ensayo sobre la ceguera",
      "la sombra del viento",
      "el codigo da vinci",
      "angeles y demonios",
      "el psicoanalista",
      "la catedral del mar",
      "yo soy malala",
      "momo",
      "la historia interminable",
      "cumbres borrascosas",
      "el retrato de dorian gray",
      "la isla del tesoro",
      "el extranjero"
    ],
    "personajes_famosos": [
      "einstein",
      "newton",
      "darwin",
      "tesla",
      "edison",
      "galileo",
      "copernico",
      "curie",
      "turing",
      "feynman",
      "da vinci",
      "miguel angel",
      "picasso",
      "dali",
      "goya",
      "cervantes",
      "shakespeare",
      "poe",
      "tolkien",
      "rowling",
      "garcia marquez",
      "neruda",
      "lorca",
      "bolivar",
      "san martin",
      "gandhi",
      "martin luther king",
      "mandela",
      "mother teresa",
      "lincoln",
      "washington",
      "churchill",
      "roosevelt",
      "kennedy",
      "hitler",
      "stalin",
      "mao",
      "napoleon",
      "cleopatra",
      "julius caesar",
      "alexander magno",
      "isabel i",
      "cristobal colon",
      "magallanes",
      "amelia earhart",
      "juan pablo ii",
      "beethoven",
      "mozart",
      "frida kahlo",
      "stephen hawking"
    ],
    "ciencia": [
      "atomo",
      "molecula",
      "celula",
      "adn",
      "gen",
      "proteina",
      "enzima",
      "evolucion",
      "seleccion natural",
      "gravedad",
      "relatividad",
      "mecanica cuantica",
      "energia",
      "materia",
      "luz",
      "espectro",
      "foton",
      "electron",
      "proton",
      "neutron",
      "quark",
      "vacuna",
      "antibiotico",
      "bacterias",
      "virus",
      "microbio",
      "ecosistema",
      "biodiversidad",
      "fotosintesis",
      "mitosis",
      "meiosis",
      "reactivo",
      "reaccion",
      "acido",
      "base",
      "ph",
      "laboratorio",
      "microscopio",
      "telescopio",
      "fosil",
      "planeta",
      "orbita",
      "atmosfera",
      "climatologia",
      "genetica",
      "neurociencia",
      "volcan",
      "sismo",
      "termodinamica",
      "astronomia"
    ],
    "ley_politica": [
      "constitucion",
      "ley",
      "decreto",
      "justicia",
      "tribunal",
      "juez",
      "abogado",
      "fiscal",
      "jurado",
      "juicio",
      "sentencia",
      "apelacion",
      "libertad condicional",
      "derecho",
      "civil",
      "penal",
      "laboral",
      "contrato",
      "acuerdo",
      "votacion",
      "elecciones",
      "democracia",
      "parlamento",
      "congreso",
      "senado",
      "presidente",
      "ministro",
      "alcalde",
      "gobernador",
      "partido",
      "campana",
      "debate",
      "oposicion",
      "gobierno",
      "estado",
      "nacion",
      "soberania",
      "constituyente",
      "referendo",
      "plebiscito",
      "impuesto",
      "presupuesto",
      "politica publica",
      "derechos humanos",
      "libertad expresion",
      "censura",
      "protesta",
      "amnistia",
      "indulto",
      "constitucional"
    ],
    "espacio": [
      "sol",
      "luna",
      "estrella",
      "galaxia",
      "via lactea",
      "planeta",
      "mercurio",
      "venus",
      "tierra",
      "marte",
      "jupiter",
      "saturno",
      "urano",
      "neptuno",
      "pluton",
      "cometa",
      "asteroide",
      "meteorito",
      "meteoro",
      "constelacion",
      "orbita",
      "gravedad",
      "eclipse",
      "agujero negro",
      "nebulosa",
      "supernova",
      "satelite",
      "cohete",
      "nave",
      "astronauta",
      "cosmonauta",
      "estacion espacial",
      "telescopio",
      "sonda",
      "rover",
      "exoplaneta",
      "luz estelar",
      "radiacion",
      "aurora",
      "atmosfera",
      "gravedad cero",
      "anillo",
      "campo magnetico",
      "polvo cosmico",
      "meteorito ferroso",
      "big bang",
      "universo",
      "meteorito rocoso",
      "luna llena",
      "cuasar"
    ],
    "suenos_pesadillas": [
      "pesadilla",
      "sueno",
      "insomnio",
      "sonambulismo",
      "dormir",
      "siesta",
      "ronquido",
      "sueno lucido",
      "monstruo",
      "fantasma",
      "persecucion",
      "caida",
      "laberinto",
      "oscuridad",
      "grito",
      "paralisis sueno",
      "reloj sin aguja",
      "espejo",
      "sombra",
      "puertas",
      "pasillo",
      "escalera",
      "techo",
      "agua",
      "fuego",
      "tormenta",
      "relampago",
      "ruido",
      "silencio",
      "despertar",
      "temblor",
      "sudor",
      "corazon rapido",
      "cueva",
      "cementerio",
      "muneco",
      "muneca",
      "risa",
      "susurro",
      "bosque",
      "niebla",
      "hospital",
      "muneco roto",
      "sangre",
      "dientes",
      "examen",
      "accidente",
      "caerse",
      "perderse",
      "puente infinito"
    ]
  },
  "caoticas": {
    "cosas_desagradables": [
      "basura",
      "vomito",
      "caca",
      "pis",
      "mocos",
      "sudor",
      "mal aliento",
      "calcetin sucio",
      "comida podrida",
      "leche cortada",
      "gusanos",
      "insectos",
      "cucaracha",
      "mosca",
      "moho",
      "mancha",
      "grasa",
      "aceite rancio",
      "pelo en comida",
      "bano sucio",
      "panal",
      "panal usado",
      "moco seco",
      "chicle pegado",
      "chicle pelo",
      "panuelo sucio",
      "basura organica",
      "pescado podrido",
      "huevo podrido",
      "basura humeda",
      "tierra en cama",
      "polvo",
      "telarana",
      "olor humedad",
      "zapatilla mojada",
      "ropa mojada",
      "sudadera humeda",
      "gusanera",
      "sarro",
      "mugre",
      "espuma sucia",
      "fregadero sucio",
      "taza inodoro",
      "trapo sucio",
      "sangre seca",
      "baba",
      "saliva",
      "escupitajo",
      "lodo",
      "orina"
    ],
    "momentos_incomodos": [
      "eructo publico",
      "pedo sonoro",
      "olvido nombre",
      "mensaje equivocado",
      "llamada erronea",
      "abrir puerta erronea",
      "tropezon",
      "caida publica",
      "ropa manchada",
      "diente con espinaca",
      "silencio incomodo",
      "abrazo no correspondido",
      "foto mala",
      "etiqueta en ropa",
      "saludo confundido",
      "beso aire",
      "olvido cumpleanos",
      "llegar tarde",
      "quedar en visto",
      "microfono abierto",
      "audio mal enviado",
      "zoom sin mute",
      "pantalon rajado",
      "gota en nariz",
      "risa fuera de lugar",
      "pregunta indiscreta",
      "respuesta fea",
      "nombre mal dicho",
      "olvidar cartera",
      "quedarte sin dinero",
      "llaves olvidadas",
      "tarjeta rechazada",
      "pagar con monedas",
      "equivocarse mesa",
      "sentarse en chicle",
      "mancha desodorante",
      "apodo publico",
      "equivocarse piso",
      "abrir chat equivocado",
      "enviar sticker raro",
      "voicemail publico",
      "caer bandeja",
      "olvidar contrasena",
      "manos sudorosas",
      "equivocarse de regalo",
      "quedarse sin papel",
      "mancha salsa",
      "voz quebrada",
      "quedarse en blanco",
      "broma mala"
    ],
    "excusas_tipicas": [
      "se me olvido",
      "no vi el mensaje",
      "me quede dormido",
      "no habia bateria",
      "se fue el internet",
      "estaba en reunion",
      "tuve un imprevisto",
      "se me hizo tarde",
      "trafico",
      "se me puncho",
      "se me rompio",
      "no me acorde",
      "tuve que trabajar",
      "se enfermo el nino",
      "me dolio el estomago",
      "se corto la luz",
      "no tenia senal",
      "me robaron",
      "perdi las llaves",
      "se me olvido la cita",
      "estaba manejando",
      "se me cruzo otra cosa",
      "tuve una emergencia",
      "no encontre parking",
      "me senti mal",
      "hubo un accidente",
      "estaba sin datos",
      "se cerro la app",
      "me equivoque de dia",
      "no estaba en casa",
      "sali a hacer un mandado",
      "tuve clase",
      "se me pasaron las horas",
      "fue un lio",
      "me quede sin credito",
      "me toco turno",
      "se me cayo el celular",
      "perdon no pude",
      "estaba en el bano",
      "no pude contestar",
      "fue el perro",
      "me quede sin saldo",
      "se me apago el movil",
      "me cambio el turno",
      "no sabia que era hoy",
      "me llamaron",
      "me quede sin gasolina",
      "se me olvido el archivo",
      "me dijeron mal",
      "me pille un taxi tarde"
    ],
    "mentiras_comunes": [
      "ya voy",
      "estoy en camino",
      "cinco minutos",
      "no he comido",
      "no fui yo",
      "no lo vi",
      "no me acuerdo",
      "no tengo dinero",
      "fue sin querer",
      "me queda perfecto",
      "no me duele",
      "me encanta",
      "te llamo luego",
      "no estoy en casa",
      "no tengo tiempo",
      "no estaba dormido",
      "no vi el mail",
      "manana empiezo",
      "esta barato",
      "solo una copa",
      "me queda cerca",
      "ya lo hice",
      "te escuche",
      "no me importa",
      "no me enoje",
      "me porto bien",
      "no me gusta",
      "estoy bien",
      "no estoy enojado",
      "lo pense",
      "no es nada",
      "no esta pesado",
      "solo mire",
      "no tengo hambre",
      "llegue justo",
      "no gaste nada",
      "no me tardo",
      "me desperte temprano",
      "estoy sano",
      "me lei las instrucciones",
      "yo no fui",
      "no me senti ofendido",
      "no he visto la serie",
      "solo un capitulo",
      "no hice trampa",
      "no comi dulces",
      "es el ultimo",
      "estoy casi listo",
      "no me molesta",
      "no sabia"
    ],
    "cosas_cuando_nadie_mira": [
      "bailar",
      "cantar",
      "hablar solo",
      "hacer cara en espejo",
      "comer de la olla",
      "probar con el dedo",
      "rascarse",
      "tirar gas",
      "revisar redes",
      "mirar el reloj",
      "estirar",
      "bostezar",
      "dormir siesta",
      "llorar",
      "reir solo",
      "hacer muecas",
      "limpiar nariz",
      "picarse dientes",
      "olfatear comida",
      "probar salsa",
      "husmear cajon",
      "espiar vecino",
      "caminar sin pantalon",
      "usar pijama todo dia",
      "saltar en la cama",
      "ver videos raros",
      "repetir memes",
      "entrenar frente espejo",
      "hablar con mascota",
      "practicar acento",
      "escribir diario",
      "ordenar cajon",
      "comer snacks",
      "cambiar canal",
      "jugar videojuego",
      "bailar tiktok",
      "bailar karaoke",
      "practicar chistes",
      "hacer sonidos",
      "tocar instrumento",
      "hacer sombra manos",
      "dibujar",
      "mirar fotos",
      "probar ropa",
      "cantar alto",
      "ponerse gafas",
      "probar peinados",
      "hacer estiramientos",
      "revisar mensajes",
      "buscar snacks"
    ],
    "cosas_que_se_pierden": [
      "llaves",
      "control remoto",
      "calcetin",
      "cargador",
      "audifonos",
      "lapiz",
      "boligrafo",
      "goma",
      "cuaderno",
      "cartera",
      "monedero",
      "tarjetas",
      "dni",
      "pasaporte",
      "gafas",
      "tapita",
      "tuerca",
      "tornillo",
      "pieza lego",
      "boton",
      "gancho",
      "horquilla",
      "pinza",
      "paraguas",
      "gorro",
      "guantes",
      "bufanda",
      "pendiente",
      "anillo",
      "collar",
      "mochila",
      "cepillo",
      "peine",
      "tijeras",
      "pegamento",
      "cinta",
      "llave usb",
      "sd",
      "mando",
      "destornillador",
      "bateria",
      "tapa tupper",
      "tapadera",
      "juguete",
      "hoja",
      "hoja deberes",
      "receta",
      "ticket",
      "tapa botella",
      "anotacion"
    ],
    "cosas_cansado": [
      "bostezar",
      "dormir",
      "roncar",
      "quedarse dormido",
      "cabecear",
      "leer mal",
      "hablar lento",
      "olvidar",
      "confundir palabras",
      "cafe",
      "te",
      "estirar",
      "acostarse",
      "caer sillon",
      "cerrar ojos",
      "siesta",
      "irse a la cama",
      "apagar luces",
      "poner alarma",
      "posponer",
      "procrastinar",
      "dejar tareas",
      "comer snack",
      "pedir comida",
      "no responder",
      "no contestar",
      "arrastrar pies",
      "hacer trampas",
      "no estudiar",
      "no entrenar",
      "quedarse en casa",
      "mirar tele",
      "ver series",
      "repetir episodio",
      "dormir sobre mesa",
      "apoyar cabeza",
      "poner musica suave",
      "manta",
      "pijama",
      "no ducharse",
      "no cocinar",
      "respirar hondo",
      "suspirar",
      "caer dormido",
      "cerrar puerta",
      "dormirse en bus",
      "olvidar tarea",
      "confundir dias",
      "bajar volumen",
      "dejar luces encendidas"
    ]
  },
  "familiares": {
    "superheroes": [
      "superman",
      "batman",
      "wonder woman",
      "spiderman",
      "iron man",
      "captain america",
      "hulk",
      "thor",
      "black widow",
      "hawkeye",
      "flash",
      "aquaman",
      "green lantern",
      "wolverine",
      "storm",
      "cyclops",
      "professor x",
      "magneto",
      "deadpool",
      "daredevil",
      "punisher",
      "dr strange",
      "black panther",
      "ant man",
      "wasp",
      "captain marvel",
      "shazam",
      "green arrow",
      "supergirl",
      "batgirl",
      "robin",
      "nightwing",
      "starfire",
      "raven",
      "beast boy",
      "cyborg",
      "doctor fate",
      "captain cold",
      "sabretooth",
      "silver surfer",
      "vision",
      "scarlet witch",
      "winter soldier",
      "falcon",
      "miles morales",
      "spider gwen",
      "loki",
      "nova",
      "ghost rider",
      "black adam"
    ],
    "animales_fantasticos": [
      "dragon",
      "unicornio",
      "fenix",
      "grifo",
      "pegaso",
      "quimera",
      "basilisco",
      "kraken",
      "sirena",
      "minotauro",
      "centauro",
      "fauno",
      "hipogrifo",
      "hidra",
      "ciclope",
      "yeti",
      "sasquatch",
      "bigfoot",
      "licantropo",
      "hombre lobo",
      "vampiro",
      "zombie",
      "fantasma",
      "duende",
      "elfo",
      "orco",
      "gnomo",
      "troll",
      "goblin",
      "hada",
      "bruja",
      "mago",
      "bronto",
      "esfinge",
      "leviatan",
      "naga",
      "salamandra",
      "griffin",
      "basilisk",
      "kobold",
      "gremlin",
      "qilin",
      "kitsune",
      "tanuki",
      "dracon",
      "wyvern",
      "hippogrifo",
      "wyvern rojo",
      "manticora",
      "roc"
    ],
    "cuentos_fantasia": [
      "cenicienta",
      "blanca nieves",
      "caperucita roja",
      "pinocho",
      "peter pan",
      "aladdin",
      "la bella y la bestia",
      "la sirena",
      "rapunzel",
      "frozen",
      "mulan",
      "hercules",
      "el rey leon",
      "el jorobado",
      "la sirena",
      "la bella durmiente",
      "hansel y gretel",
      "el gato con botas",
      "el patito feo",
      "los tres cerditos",
      "la flauta magica",
      "jack y las habichuelas",
      "alicia",
      "oz",
      "el mago de oz",
      "el principito",
      "momo",
      "la historia interminable",
      "el grunon",
      "narnia",
      "el bosque magico",
      "la casa de chocolate",
      "la brujula dorada",
      "el castillo ambulante",
      "el viaje de chihiro",
      "mi vecino totoro",
      "pony magico",
      "dragones",
      "hadas",
      "gnomos",
      "duendes",
      "magos",
      "brujas",
      "castillos",
      "princesas",
      "caballeros",
      "bosques",
      "el flautista",
      "pulgarcito",
      "ricitos de oro"
    ],
    "cosas_del_cole": [
      "mochila",
      "estuche",
      "lapiz",
      "boligrafo",
      "goma",
      "sacapuntas",
      "regla",
      "cuaderno",
      "libro",
      "pizarra",
      "tiza",
      "rotulador",
      "marcador",
      "carpeta",
      "pegamento",
      "tijeras",
      "pintura",
      "acuarela",
      "mochila ruedas",
      "agenda",
      "deberes",
      "examen",
      "recreo",
      "patio",
      "comedor",
      "uniforme",
      "bata",
      "pupitre",
      "silla",
      "clase",
      "profesor",
      "maestra",
      "director",
      "biblioteca",
      "laboratorio",
      "gimnasio",
      "pista",
      "porterias",
      "balon",
      "merienda",
      "cantina",
      "salida",
      "excursion",
      "campamento",
      "mapa",
      "globo terrestre",
      "plastilina",
      "papel",
      "cartulina",
      "compas",
      "calculadora"
    ],
    "chucherias": [
      "chicle",
      "piruleta",
      "caramelos",
      "regaliz",
      "gominolas",
      "gomitas",
      "chuches",
      "chocolate",
      "bombones",
      "marshmallow",
      "malvavisco",
      "paleta",
      "taffy",
      "jellybean",
      "ositos goma",
      "gusanos goma",
      "coca cola gelatina",
      "caramelo duro",
      "caramelo blando",
      "caramelo masticable",
      "toffee",
      "turron",
      "mazapan",
      "polvoron",
      "confites",
      "lacasitos",
      "m and m",
      "kitkat",
      "oreo",
      "kinder",
      "huesitos",
      "sugus",
      "palotes",
      "ladrillo azucar",
      "nube",
      "nube rosa",
      "nube blanca",
      "caramelos menta",
      "chicle menta",
      "chicle fresa",
      "caramelo fresa",
      "caramelo limon",
      "piruleta corazon",
      "chupachups",
      "alfajor",
      "caramelo cafe",
      "caramelo menta extra",
      "chocolate blanco",
      "chocolate negro",
      "golosina acida"
    ],
    "juguetes": [
      "pelota",
      "muneca",
      "muneco",
      "peluche",
      "coche",
      "tren",
      "barco",
      "avion",
      "robot",
      "dinosaurio",
      "lego",
      "bloques",
      "puzzle",
      "rompecabezas",
      "canicas",
      "trompo",
      "yoyo",
      "yo yo",
      "plastilina",
      "slinky",
      "patines",
      "bici",
      "patinete",
      "cometa",
      "set cocina",
      "set medico",
      "set herramientas",
      "caja magia",
      "cartas",
      "domino",
      "ajedrez",
      "damas",
      "monopoly",
      "jenga",
      "oca",
      "parchis",
      "lanza agua",
      "pistola agua",
      "juego pesca",
      "juego memoria",
      "tren pista",
      "pista autos",
      "avion rc",
      "dron",
      "muneco accion",
      "cubo rubik",
      "scalextric",
      "hula hula",
      "yo yo luz",
      "pistola laser"
    ],
    "dibujos_animados": [
      "mickey",
      "minnie",
      "donald",
      "goofy",
      "pluto",
      "tom y jerry",
      "bob esponja",
      "patrick",
      "calamardo",
      "dora",
      "botas",
      "diego",
      "peppa pig",
      "george",
      "bluey",
      "bingo",
      "paw patrol",
      "chase",
      "marshall",
      "skye",
      "rocky",
      "ruben",
      "blaze",
      "pj masks",
      "catboy",
      "owlette",
      "gekko",
      "pepa",
      "gumball",
      "darwin",
      "clarence",
      "scoobydoo",
      "shaggy",
      "the simpsons",
      "homer",
      "marge",
      "bart",
      "lisa",
      "maggie",
      "futurama",
      "bender",
      "rick and morty",
      "morty",
      "gravity falls",
      "dipper",
      "mabel",
      "phineas",
      "ferb",
      "pokemon",
      "pikachu"
    ]
  }
}
