window.WORDS = {
  "easy": {
    "food": [
      "pizza",
      "apple",
      "hamburger",
      "pear",
      "banana",
      "orange",
      "grape",
      "watermelon",
      "melon",
      "strawberry",
      "cherry",
      "lemon",
      "lime",
      "mango",
      "papaya",
      "kiwi",
      "peach",
      "apricot",
      "plum",
      "pomegranate",
      "tomato",
      "lettuce",
      "carrot",
      "cucumber",
      "onion",
      "garlic",
      "potato",
      "rice",
      "pasta",
      "bread",
      "cheese",
      "milk",
      "yogurt",
      "egg",
      "ham",
      "chicken",
      "fish",
      "tuna",
      "sausage",
      "soup",
      "salad",
      "empanada",
      "tacos",
      "burrito",
      "arepa",
      "sushi",
      "lasagna",
      "croquette",
      "ice cream",
      "cookie",
      "chocolate"
    ],
    "animals": [
      "dog",
      "cat",
      "elephant",
      "lion",
      "tiger",
      "giraffe",
      "zebra",
      "monkey",
      "gorilla",
      "hippopotamus",
      "rhinoceros",
      "crocodile",
      "turtle",
      "snake",
      "lizard",
      "rabbit",
      "hamster",
      "mouse",
      "squirrel",
      "bear",
      "wolf",
      "fox",
      "horse",
      "cow",
      "pig",
      "sheep",
      "goat",
      "chicken",
      "rooster",
      "duck",
      "goose",
      "turkey",
      "fish",
      "shark",
      "dolphin",
      "whale",
      "octopus",
      "crab",
      "shrimp",
      "butterfly",
      "bee",
      "ant",
      "beetle",
      "bird",
      "parrot",
      "eagle",
      "owl",
      "dove",
      "penguin",
      "flamingo"
    ],
    "household_objects": [
      "sofa",
      "table",
      "chair",
      "lamp",
      "refrigerator",
      "oven",
      "microwave",
      "toaster",
      "coffee maker",
      "kettle",
      "knife",
      "fork",
      "spoon",
      "plate",
      "glass",
      "cup",
      "tablecloth",
      "curtain",
      "mirror",
      "rug",
      "bed",
      "pillow",
      "sheet",
      "mattress",
      "closet",
      "dresser",
      "shelf",
      "desk",
      "television",
      "remote",
      "clock",
      "picture",
      "vase",
      "broom",
      "dustpan",
      "vacuum cleaner",
      "iron",
      "washing machine",
      "dryer",
      "detergent",
      "soap",
      "towel",
      "toilet paper",
      "brush",
      "toothpaste",
      "shower",
      "faucet",
      "sink",
      "toilet",
      "fan"
    ],
    "transport": [
      "car",
      "automobile",
      "bus",
      "coach",
      "truck",
      "pickup truck",
      "motorcycle",
      "bicycle",
      "scooter",
      "train",
      "tram",
      "subway",
      "taxi",
      "airplane",
      "helicopter",
      "boat",
      "sailboat",
      "yacht",
      "cruise ship",
      "submarine",
      "motorboat",
      "canoe",
      "kayak",
      "skate",
      "skateboard",
      "balloon",
      "airship",
      "rocket",
      "spaceship",
      "tractor",
      "ambulance",
      "fire truck",
      "tanker truck",
      "van",
      "trailer",
      "crane",
      "cable car",
      "funicular",
      "carriage",
      "cart",
      "segway",
      "jet ski",
      "tricycle",
      "electric bike",
      "bullet train",
      "freight train",
      "school bus",
      "rickshaw",
      "camper",
      "hoverboard"
    ],
    "clothing": [
      "t-shirt",
      "pants",
      "jeans",
      "shorts",
      "skirt",
      "dress",
      "coat",
      "jacket",
      "sweater",
      "sweatshirt",
      "shirt",
      "blouse",
      "socks",
      "stockings",
      "shoes",
      "sneakers",
      "boots",
      "sandals",
      "cap",
      "hat",
      "scarf",
      "gloves",
      "belt",
      "tie",
      "bow tie",
      "parka",
      "raincoat",
      "pajamas",
      "robe",
      "underwear",
      "bra",
      "boxers",
      "bikini",
      "swimsuit",
      "suit",
      "uniform",
      "vest",
      "overalls",
      "leggings",
      "tights",
      "handkerchief",
      "headband",
      "balaclava",
      "windbreaker",
      "cape",
      "poncho",
      "bathrobe",
      "tank top"
    ],
    "common_places": [
      "school",
      "college",
      "high school",
      "university",
      "hospital",
      "clinic",
      "park",
      "square",
      "library",
      "supermarket",
      "market",
      "store",
      "pharmacy",
      "bank",
      "office",
      "house",
      "apartment",
      "flat",
      "neighborhood",
      "station",
      "airport",
      "cinema",
      "theater",
      "museum",
      "restaurant",
      "cafe",
      "bar",
      "gym",
      "pool",
      "stadium",
      "church",
      "city hall",
      "police station",
      "fire station",
      "hotel",
      "gas station",
      "beach",
      "mountain",
      "forest",
      "road",
      "bridge",
      "river",
      "lake",
      "port",
      "marina",
      "indoor stadium",
      "sports center",
      "daycare",
      "shopping mall",
      "health center"
    ],
    "colors": [
      "red",
      "blue",
      "yellow",
      "green",
      "orange",
      "purple",
      "violet",
      "pink",
      "black",
      "white",
      "gray",
      "brown",
      "beige",
      "turquoise",
      "cyan",
      "magenta",
      "fuchsia",
      "lime",
      "olive",
      "coral",
      "mustard",
      "ochre",
      "tan",
      "lavender",
      "teal",
      "emerald",
      "ruby",
      "sapphire",
      "gold",
      "silver",
      "copper",
      "bronze",
      "terracotta",
      "salmon",
      "cherry",
      "pastel",
      "cream",
      "pearl",
      "anthracite",
      "graphite",
      "ice",
      "ivory",
      "sand",
      "melon",
      "aqua",
      "charcoal",
      "amber",
      "sky blue",
      "pistachio",
      "eggplant",
      "light gray"
    ],
    "sports": [
      "soccer",
      "basketball",
      "tennis",
      "paddle tennis",
      "volleyball",
      "baseball",
      "american football",
      "rugby",
      "golf",
      "hockey",
      "ice hockey",
      "swimming",
      "athletics",
      "cycling",
      "boxing",
      "martial arts",
      "judo",
      "karate",
      "taekwondo",
      "fencing",
      "gymnastics",
      "rhythmic gymnastics",
      "skating",
      "figure skating",
      "surfing",
      "windsurfing",
      "kitesurfing",
      "sailing",
      "rowing",
      "canoeing",
      "climbing",
      "mountaineering",
      "hiking",
      "skiing",
      "snowboarding",
      "ping pong",
      "table tennis",
      "badminton",
      "squash",
      "handball",
      "water polo",
      "triathlon",
      "pentathlon",
      "darts",
      "archery",
      "weightlifting",
      "motorsport",
      "motorcycling",
      "curling",
      "lacrosse"
    ],
    "toys_games": [
      "ball",
      "beach ball",
      "marbles",
      "kite",
      "paper airplane",
      "puzzle",
      "jigsaw puzzle",
      "lego",
      "blocks",
      "doll",
      "action figure",
      "stuffed animal",
      "toy car",
      "toy train",
      "robot",
      "toy dinosaur",
      "playhouse",
      "toy kitchen",
      "doctor set",
      "play dough",
      "slinky",
      "yoyo",
      "spinning top",
      "cards",
      "lottery",
      "domino",
      "chess",
      "checkers",
      "game of goose",
      "parcheesi",
      "monopoly",
      "jenga",
      "video games",
      "console",
      "game tablet",
      "board game",
      "race track",
      "rubik's cube",
      "roller skates",
      "balance bike",
      "bubbles",
      "puppet",
      "marionette",
      "water gun",
      "toy golf club",
      "paint set",
      "diabolo",
      "jump rope",
      "dart gun"
    ]
  },
  "medium": {
    "professions": [
      "doctor",
      "nurse",
      "dentist",
      "veterinarian",
      "teacher",
      "professor",
      "engineer",
      "architect",
      "lawyer",
      "judge",
      "police officer",
      "firefighter",
      "pilot",
      "flight attendant",
      "chef",
      "waiter",
      "barista",
      "baker",
      "butcher",
      "fishmonger",
      "farmer",
      "gardener",
      "mechanic",
      "electrician",
      "plumber",
      "carpenter",
      "painter",
      "hairdresser",
      "makeup artist",
      "designer",
      "programmer",
      "analyst",
      "accountant",
      "banker",
      "salesperson",
      "sales representative",
      "manager",
      "entrepreneur",
      "journalist",
      "photographer",
      "actor",
      "actress",
      "singer",
      "musician",
      "delivery driver",
      "taxi driver",
      "driver",
      "truck driver",
      "librarian",
      "translator"
    ],
    "famous_movies": [
      "the godfather",
      "titanic",
      "avatar",
      "star wars",
      "the lord of the rings",
      "harry potter",
      "the matrix",
      "jurassic park",
      "indiana jones",
      "back to the future",
      "forrest gump",
      "toy story",
      "the lion king",
      "the little mermaid",
      "aladdin",
      "frozen",
      "coco",
      "up",
      "shrek",
      "taken",
      "gladiator",
      "braveheart",
      "inception",
      "interstellar",
      "the dark knight",
      "batman begins",
      "spiderman",
      "iron man",
      "avengers",
      "guardians of the galaxy",
      "black panther",
      "mad max fury road",
      "la la land",
      "whiplash",
      "parasite",
      "city of god",
      "pan's labyrinth",
      "pulp fiction",
      "fight club",
      "se7en",
      "get out",
      "the big lebowski",
      "rocky",
      "rambo",
      "terminator",
      "alien",
      "blade runner",
      "jaws",
      "back to the future 2",
      "the godfather 2"
    ],
    "musical_instruments": [
      "guitar",
      "bass",
      "violin",
      "viola",
      "cello",
      "double bass",
      "piano",
      "keyboard",
      "drums",
      "drum",
      "bongos",
      "congas",
      "timpani",
      "maracas",
      "triangle",
      "flute",
      "recorder",
      "clarinet",
      "oboe",
      "bassoon",
      "trumpet",
      "trombone",
      "tuba",
      "saxophone",
      "harp",
      "accordion",
      "bandoneon",
      "ukulele",
      "banjo",
      "mandolin",
      "sitar",
      "lyre",
      "cymbal",
      "organ",
      "synthesizer",
      "kazoo",
      "harmonica",
      "castanets",
      "xylophone",
      "vibraphone",
      "metallophone",
      "tambourine",
      "claves",
      "guiro",
      "cuica",
      "dulzaina",
      "bagpipes",
      "didgeridoo",
      "kalimba",
      "ocarina"
    ],
    "countries_cities": [
      "spain",
      "portugal",
      "france",
      "italy",
      "germany",
      "united kingdom",
      "ireland",
      "scotland",
      "wales",
      "switzerland",
      "belgium",
      "netherlands",
      "sweden",
      "norway",
      "finland",
      "denmark",
      "iceland",
      "poland",
      "greece",
      "turkey",
      "russia",
      "china",
      "japan",
      "korea",
      "india",
      "pakistan",
      "australia",
      "new zealand",
      "united states",
      "canada",
      "mexico",
      "brazil",
      "argentina",
      "chile",
      "peru",
      "colombia",
      "venezuela",
      "ecuador",
      "bolivia",
      "paraguay",
      "uruguay",
      "cuba",
      "dominican republic",
      "panama",
      "costa rica",
      "guatemala",
      "honduras",
      "nicaragua",
      "el salvador",
      "morocco"
    ],
    "technology": [
      "smartphone",
      "tablet",
      "laptop",
      "pc",
      "smartwatch",
      "headphones",
      "bluetooth speaker",
      "camera",
      "drone",
      "console",
      "video game",
      "router",
      "modem",
      "wifi",
      "bluetooth",
      "usb",
      "hard drive",
      "ssd",
      "cloud",
      "app",
      "browser",
      "search engine",
      "email",
      "message",
      "chat",
      "social network",
      "streaming",
      "podcast",
      "gps",
      "map",
      "virtual assistant",
      "artificial intelligence",
      "robot",
      "printer",
      "scanner",
      "keyboard",
      "mouse",
      "monitor",
      "projector",
      "virtual reality",
      "augmented reality",
      "microphone",
      "webcam",
      "charger",
      "power bank",
      "smart tv",
      "home automation",
      "sensor",
      "wearable",
      "qr code"
    ],
    "celebrations": [
      "birthday",
      "christmas",
      "new year",
      "three kings",
      "easter",
      "halloween",
      "carnival",
      "valentine's day",
      "midsummer",
      "children's day",
      "father's day",
      "mother's day",
      "wedding",
      "baptism",
      "communion",
      "graduation",
      "anniversary",
      "bachelor party",
      "baby shower",
      "surprise party",
      "opening",
      "festival",
      "fair",
      "pilgrimage",
      "patron saint festival",
      "new year's eve",
      "end of school",
      "barbecue",
      "picnic",
      "sleepover",
      "family reunion",
      "farewell",
      "welcome",
      "pool party",
      "beach party",
      "costume party",
      "theme party",
      "children's party",
      "house party",
      "street party",
      "music festival",
      "concert",
      "first communion",
      "quinceañera",
      "brazilian carnival",
      "hanukkah",
      "ramadan",
      "eid",
      "thanksgiving",
      "hawaiian party"
    ],
    "vacations": [
      "beach",
      "mountain",
      "camping",
      "hotel",
      "hostel",
      "cruise",
      "resort",
      "spa",
      "thermal spa",
      "excursion",
      "route",
      "road trip",
      "backpacker",
      "trip",
      "tourism",
      "walk",
      "guided tour",
      "theme park",
      "museum",
      "city",
      "town",
      "island",
      "lake",
      "river",
      "forest",
      "safari",
      "adventure",
      "skiing",
      "snowboarding",
      "diving",
      "snorkeling",
      "surfing",
      "winter vacation",
      "summer vacation",
      "family vacation",
      "long weekend",
      "weekend",
      "getaway",
      "photography",
      "car rental",
      "suitcase",
      "passport",
      "visa",
      "map",
      "itinerary",
      "airport",
      "station",
      "souvenirs",
      "hiking",
      "visiting family"
    ],
    "stores_brands": [
      "supermarket",
      "hypermarket",
      "corner store",
      "pharmacy",
      "bakery",
      "pastry shop",
      "butcher shop",
      "fish market",
      "fruit shop",
      "hardware store",
      "stationery store",
      "bookstore",
      "shoe store",
      "perfume shop",
      "jewelry store",
      "watch shop",
      "optician",
      "gas station",
      "market",
      "clothing store",
      "sports store",
      "toy store",
      "tech store",
      "electronics",
      "furniture store",
      "outlet",
      "bazaar",
      "kiosk",
      "flower shop",
      "tobacco shop",
      "gift shop",
      "pet store",
      "bike shop",
      "camera store",
      "grocery store",
      "delicatessen",
      "organic store",
      "thrift store",
      "online store",
      "amazon",
      "ikea",
      "zara",
      "nike",
      "adidas",
      "apple",
      "google",
      "microsoft",
      "samsung",
      "carrefour",
      "walmart"
    ],
    "desserts_sweets": [
      "ice cream",
      "cake",
      "pastry",
      "sponge cake",
      "cupcake",
      "muffin",
      "brownie",
      "cookie",
      "bonbon",
      "chocolate",
      "candy",
      "flan",
      "custard",
      "rice pudding",
      "churros",
      "fritters",
      "donut",
      "doughnut",
      "croissant",
      "mille-feuille",
      "tiramisu",
      "panna cotta",
      "jelly",
      "mousse",
      "sorbet",
      "yogurt",
      "strawberries and cream",
      "crema catalana",
      "tocino de cielo",
      "custards",
      "alfajor",
      "polvoron",
      "marzipan",
      "french toast",
      "king cake",
      "meringue",
      "truffle",
      "liqueur bonbon",
      "jam",
      "honey",
      "waffle",
      "popsicle",
      "marshmallow",
      "chewing gum",
      "lollipop",
      "cotton candy",
      "cheesecake",
      "crepe",
      "wafer"
    ]
  },
  "hard": {
    "abstract_concepts": [
      "freedom",
      "justice",
      "equality",
      "love",
      "hate",
      "happiness",
      "sadness",
      "success",
      "failure",
      "time",
      "eternity",
      "destiny",
      "luck",
      "power",
      "peace",
      "war",
      "truth",
      "lie",
      "faith",
      "hope",
      "fear",
      "anxiety",
      "stress",
      "creativity",
      "beauty",
      "meaning",
      "purpose",
      "identity",
      "memory",
      "consciousness",
      "empathy",
      "pride",
      "humility",
      "ambition",
      "morality",
      "ethics",
      "responsibility",
      "respect",
      "honor",
      "loyalty",
      "patience",
      "resilience",
      "nostalgia",
      "loneliness",
      "trust",
      "commitment",
      "change",
      "order",
      "chaos",
      "silence"
    ],
    "emotions": [
      "joy",
      "sadness",
      "fear",
      "anger",
      "disgust",
      "surprise",
      "anxiety",
      "nervousness",
      "calm",
      "serenity",
      "pride",
      "shame",
      "guilt",
      "envy",
      "jealousy",
      "gratitude",
      "enthusiasm",
      "boredom",
      "frustration",
      "nostalgia",
      "hope",
      "despair",
      "empathy",
      "compassion",
      "melancholy",
      "euphoria",
      "relief",
      "tenderness",
      "confusion",
      "shyness",
      "admiration",
      "indifference",
      "disappointment",
      "disillusionment",
      "panic",
      "resentment",
      "grudge",
      "insecurity",
      "satisfaction",
      "irritation",
      "embarrassment",
      "affection",
      "attachment",
      "dislike",
      "amazement",
      "happiness",
      "anguish",
      "tension",
      "helplessness",
      "excitement"
    ],
    "historical_periods": [
      "prehistory",
      "paleolithic",
      "neolithic",
      "ancient age",
      "middle ages",
      "modern age",
      "contemporary age",
      "roman empire",
      "classical greece",
      "ancient egypt",
      "mesopotamia",
      "bronze age",
      "iron age",
      "renaissance",
      "baroque",
      "enlightenment",
      "industrial revolution",
      "french revolution",
      "victorian era",
      "cold war",
      "world war I",
      "world war II",
      "colonization",
      "golden age",
      "ice age",
      "stone age",
      "feudalism",
      "crusades",
      "reformation",
      "counter-reformation",
      "discovery of america",
      "19th century",
      "20th century",
      "21st century",
      "modernism",
      "realism",
      "romanticism",
      "impressionism",
      "modernity",
      "contemporary",
      "post-war",
      "ancient china",
      "dark ages",
      "belle epoque",
      "roaring twenties",
      "swinging sixties",
      "spanish golden age",
      "russian revolution",
      "civil war",
      "classical antiquity"
    ],
    "books_literature": [
      "don quixote",
      "one hundred years of solitude",
      "the odyssey",
      "the iliad",
      "romeo and juliet",
      "hamlet",
      "macbeth",
      "the little prince",
      "the alchemist",
      "pride and prejudice",
      "sherlock holmes",
      "dracula",
      "frankenstein",
      "moby dick",
      "war and peace",
      "crime and punishment",
      "les miserables",
      "the count of monte cristo",
      "dune",
      "1984",
      "animal farm",
      "fahrenheit 451",
      "the hobbit",
      "the lord of the rings",
      "harry potter",
      "the hunger games",
      "twilight",
      "anna karenina",
      "the name of the rose",
      "the divine comedy",
      "paradise lost",
      "the metamorphosis",
      "the trial",
      "hopscotch",
      "the tunnel",
      "the house of the spirits",
      "love in the time of cholera",
      "blindness",
      "the shadow of the wind",
      "the da vinci code",
      "angels and demons",
      "the analyst",
      "cathedral of the sea",
      "i am malala",
      "momo",
      "the neverending story",
      "wuthering heights",
      "the picture of dorian gray",
      "treasure island",
      "the stranger"
    ],
    "famous_people": [
      "einstein",
      "newton",
      "darwin",
      "tesla",
      "edison",
      "galileo",
      "copernicus",
      "curie",
      "turing",
      "feynman",
      "da vinci",
      "michelangelo",
      "picasso",
      "dali",
      "goya",
      "cervantes",
      "shakespeare",
      "poe",
      "tolkien",
      "rowling",
      "garcia marquez",
      "neruda",
      "lorca",
      "bolivar",
      "san martin",
      "gandhi",
      "martin luther king",
      "mandela",
      "mother teresa",
      "lincoln",
      "washington",
      "churchill",
      "roosevelt",
      "kennedy",
      "hitler",
      "stalin",
      "mao",
      "napoleon",
      "cleopatra",
      "julius caesar",
      "alexander the great",
      "elizabeth I",
      "christopher columbus",
      "magellan",
      "amelia earhart",
      "john paul II",
      "beethoven",
      "mozart",
      "frida kahlo",
      "stephen hawking"
    ],
    "science": [
      "atom",
      "molecule",
      "cell",
      "dna",
      "gene",
      "protein",
      "enzyme",
      "evolution",
      "natural selection",
      "gravity",
      "relativity",
      "quantum mechanics",
      "energy",
      "matter",
      "light",
      "spectrum",
      "photon",
      "electron",
      "proton",
      "neutron",
      "quark",
      "vaccine",
      "antibiotic",
      "bacteria",
      "virus",
      "microbe",
      "ecosystem",
      "biodiversity",
      "photosynthesis",
      "mitosis",
      "meiosis",
      "reagent",
      "reaction",
      "acid",
      "base",
      "ph",
      "laboratory",
      "microscope",
      "telescope",
      "fossil",
      "planet",
      "orbit",
      "atmosphere",
      "climatology",
      "genetics",
      "neuroscience",
      "volcano",
      "earthquake",
      "thermodynamics",
      "astronomy"
    ],
    "law_politics": [
      "constitution",
      "law",
      "decree",
      "justice",
      "court",
      "judge",
      "lawyer",
      "prosecutor",
      "jury",
      "trial",
      "sentence",
      "appeal",
      "parole",
      "right",
      "civil",
      "criminal",
      "labor",
      "contract",
      "agreement",
      "vote",
      "election",
      "democracy",
      "parliament",
      "congress",
      "senate",
      "president",
      "minister",
      "mayor",
      "governor",
      "party",
      "campaign",
      "debate",
      "opposition",
      "government",
      "state",
      "nation",
      "sovereignty",
      "constituent",
      "referendum",
      "plebiscite",
      "tax",
      "budget",
      "public policy",
      "human rights",
      "freedom of speech",
      "censorship",
      "protest",
      "amnesty",
      "pardon",
      "constitutional"
    ],
    "space": [
      "sun",
      "moon",
      "star",
      "galaxy",
      "milky way",
      "planet",
      "mercury",
      "venus",
      "earth",
      "mars",
      "jupiter",
      "saturn",
      "uranus",
      "neptune",
      "pluto",
      "comet",
      "asteroid",
      "meteorite",
      "meteor",
      "constellation",
      "orbit",
      "gravity",
      "eclipse",
      "black hole",
      "nebula",
      "supernova",
      "satellite",
      "rocket",
      "spaceship",
      "astronaut",
      "cosmonaut",
      "space station",
      "telescope",
      "probe",
      "rover",
      "exoplanet",
      "starlight",
      "radiation",
      "aurora",
      "atmosphere",
      "zero gravity",
      "ring",
      "magnetic field",
      "cosmic dust",
      "iron meteorite",
      "big bang",
      "universe",
      "rocky meteorite",
      "full moon",
      "quasar"
    ],
    "dreams_nightmares": [
      "nightmare",
      "dream",
      "insomnia",
      "sleepwalking",
      "sleeping",
      "nap",
      "snoring",
      "lucid dream",
      "monster",
      "ghost",
      "chase",
      "falling",
      "labyrinth",
      "darkness",
      "scream",
      "sleep paralysis",
      "clock without hands",
      "mirror",
      "shadow",
      "doors",
      "hallway",
      "stairs",
      "ceiling",
      "water",
      "fire",
      "storm",
      "lightning",
      "noise",
      "silence",
      "waking up",
      "trembling",
      "sweat",
      "racing heart",
      "cave",
      "cemetery",
      "doll",
      "puppet",
      "laughter",
      "whisper",
      "forest",
      "fog",
      "hospital",
      "broken doll",
      "blood",
      "teeth",
      "exam",
      "accident",
      "falling down",
      "getting lost",
      "endless bridge"
    ]
  },
  "chaotic": {
    "disgusting_things": [
      "garbage",
      "vomit",
      "poop",
      "pee",
      "snot",
      "sweat",
      "bad breath",
      "dirty sock",
      "rotten food",
      "sour milk",
      "worms",
      "insects",
      "cockroach",
      "fly",
      "mold",
      "stain",
      "grease",
      "rancid oil",
      "hair in food",
      "dirty bathroom",
      "diaper",
      "used diaper",
      "dried snot",
      "stuck gum",
      "gum in hair",
      "dirty tissue",
      "organic waste",
      "rotten fish",
      "rotten egg",
      "wet garbage",
      "dirt in bed",
      "dust",
      "cobweb",
      "musty smell",
      "wet sneaker",
      "wet clothes",
      "damp sweatshirt",
      "maggots",
      "tartar",
      "grime",
      "dirty foam",
      "dirty sink",
      "toilet bowl",
      "dirty rag",
      "dried blood",
      "drool",
      "saliva",
      "spit",
      "mud",
      "urine"
    ],
    "awkward_moments": [
      "public burp",
      "loud fart",
      "forgetting name",
      "wrong message",
      "wrong call",
      "opening wrong door",
      "stumbling",
      "public fall",
      "stained clothes",
      "spinach in teeth",
      "awkward silence",
      "unreturned hug",
      "bad photo",
      "tag on clothes",
      "confused greeting",
      "air kiss",
      "forgetting birthday",
      "arriving late",
      "left on read",
      "open microphone",
      "wrong audio sent",
      "zoom without mute",
      "ripped pants",
      "drop on nose",
      "inappropriate laugh",
      "indiscreet question",
      "rude answer",
      "mispronounced name",
      "forgetting wallet",
      "running out of money",
      "forgotten keys",
      "declined card",
      "paying with coins",
      "wrong table",
      "sitting on gum",
      "deodorant stain",
      "public nickname",
      "wrong floor",
      "opening wrong chat",
      "sending weird sticker",
      "public voicemail",
      "dropping tray",
      "forgetting password",
      "sweaty hands",
      "wrong gift",
      "running out of paper",
      "sauce stain",
      "cracking voice",
      "going blank",
      "bad joke"
    ],
    "typical_excuses": [
      "i forgot",
      "didn't see the message",
      "i overslept",
      "no battery",
      "internet went out",
      "i was in a meeting",
      "i had something come up",
      "i was running late",
      "traffic",
      "got a flat tire",
      "it broke",
      "i didn't remember",
      "i had to work",
      "the kid got sick",
      "my stomach hurt",
      "power went out",
      "no signal",
      "i got robbed",
      "i lost my keys",
      "i forgot the appointment",
      "i was driving",
      "something else came up",
      "i had an emergency",
      "couldn't find parking",
      "i felt sick",
      "there was an accident",
      "i had no data",
      "the app closed",
      "i got the day wrong",
      "i wasn't home",
      "i went to do an errand",
      "i had class",
      "lost track of time",
      "it was a mess",
      "i ran out of credit",
      "i had an appointment",
      "i dropped my phone",
      "sorry i couldn't",
      "i was in the bathroom",
      "couldn't answer",
      "it was the dog",
      "i ran out of balance",
      "my phone died",
      "my shift changed",
      "i didn't know it was today",
      "they called me",
      "i ran out of gas",
      "i forgot the file",
      "they told me wrong",
      "i caught a late taxi"
    ],
    "common_lies": [
      "i'm coming",
      "i'm on my way",
      "five minutes",
      "i haven't eaten",
      "it wasn't me",
      "i didn't see it",
      "i don't remember",
      "i have no money",
      "it was an accident",
      "it fits perfectly",
      "it doesn't hurt",
      "i love it",
      "i'll call you later",
      "i'm not home",
      "i have no time",
      "i wasn't sleeping",
      "i didn't see the email",
      "i'll start tomorrow",
      "it's cheap",
      "just one drink",
      "it's close by",
      "i already did it",
      "i heard you",
      "i don't care",
      "i'm not angry",
      "i'll behave",
      "i don't like it",
      "i'm fine",
      "i'm not mad",
      "i thought about it",
      "it's nothing",
      "it's not heavy",
      "just browsing",
      "i'm not hungry",
      "i arrived just in time",
      "i didn't spend anything",
      "i won't be long",
      "i woke up early",
      "i'm healthy",
      "i read the instructions",
      "it wasn't me",
      "i wasn't offended",
      "i haven't seen the show",
      "just one episode",
      "i didn't cheat",
      "i didn't eat sweets",
      "it's the last one",
      "i'm almost ready",
      "it doesn't bother me",
      "i didn't know"
    ],
    "things_when_nobody_watches": [
      "dancing",
      "singing",
      "talking to yourself",
      "making faces in mirror",
      "eating from pot",
      "tasting with finger",
      "scratching",
      "passing gas",
      "checking social media",
      "looking at clock",
      "stretching",
      "yawning",
      "taking nap",
      "crying",
      "laughing alone",
      "making faces",
      "cleaning nose",
      "picking teeth",
      "sniffing food",
      "tasting sauce",
      "snooping in drawer",
      "spying on neighbor",
      "walking without pants",
      "wearing pajamas all day",
      "jumping on bed",
      "watching weird videos",
      "repeating memes",
      "training in front of mirror",
      "talking to pet",
      "practicing accent",
      "writing diary",
      "organizing drawer",
      "eating snacks",
      "changing channel",
      "playing video game",
      "dancing tiktok",
      "karaoke dancing",
      "practicing jokes",
      "making sounds",
      "playing instrument",
      "making hand shadows",
      "drawing",
      "looking at photos",
      "trying on clothes",
      "singing loud",
      "putting on glasses",
      "trying hairstyles",
      "doing stretches",
      "checking messages",
      "looking for snacks"
    ],
    "things_that_get_lost": [
      "keys",
      "remote control",
      "sock",
      "charger",
      "headphones",
      "pencil",
      "pen",
      "eraser",
      "notebook",
      "wallet",
      "coin purse",
      "cards",
      "id",
      "passport",
      "glasses",
      "cap",
      "nut",
      "screw",
      "lego piece",
      "button",
      "hook",
      "hairpin",
      "clip",
      "umbrella",
      "hat",
      "gloves",
      "scarf",
      "earring",
      "ring",
      "necklace",
      "backpack",
      "brush",
      "comb",
      "scissors",
      "glue",
      "tape",
      "usb drive",
      "sd card",
      "controller",
      "screwdriver",
      "battery",
      "tupperware lid",
      "pot lid",
      "toy",
      "sheet",
      "homework sheet",
      "recipe",
      "receipt",
      "bottle cap",
      "note"
    ],
    "things_when_tired": [
      "yawning",
      "sleeping",
      "snoring",
      "falling asleep",
      "nodding off",
      "reading wrong",
      "talking slow",
      "forgetting",
      "mixing up words",
      "coffee",
      "tea",
      "stretching",
      "lying down",
      "falling on couch",
      "closing eyes",
      "nap",
      "going to bed",
      "turning off lights",
      "setting alarm",
      "postponing",
      "procrastinating",
      "leaving tasks",
      "eating snack",
      "ordering food",
      "not answering",
      "not replying",
      "dragging feet",
      "cheating",
      "not studying",
      "not training",
      "staying home",
      "watching tv",
      "watching series",
      "rewatching episode",
      "sleeping on table",
      "resting head",
      "playing soft music",
      "blanket",
      "pajamas",
      "not showering",
      "not cooking",
      "breathing deep",
      "sighing",
      "falling asleep",
      "closing door",
      "falling asleep on bus",
      "forgetting task",
      "mixing up days",
      "lowering volume",
      "leaving lights on"
    ]
  },
  "family": {
    "superheroes": [
      "superman",
      "batman",
      "wonder woman",
      "spiderman",
      "iron man",
      "captain america",
      "hulk",
      "thor",
      "black widow",
      "hawkeye",
      "flash",
      "aquaman",
      "green lantern",
      "wolverine",
      "storm",
      "cyclops",
      "professor x",
      "magneto",
      "deadpool",
      "daredevil",
      "punisher",
      "dr strange",
      "black panther",
      "ant man",
      "wasp",
      "captain marvel",
      "shazam",
      "green arrow",
      "supergirl",
      "batgirl",
      "robin",
      "nightwing",
      "starfire",
      "raven",
      "beast boy",
      "cyborg",
      "doctor fate",
      "captain cold",
      "sabretooth",
      "silver surfer",
      "vision",
      "scarlet witch",
      "winter soldier",
      "falcon",
      "miles morales",
      "spider gwen",
      "loki",
      "nova",
      "ghost rider",
      "black adam"
    ],
    "fantastic_animals": [
      "dragon",
      "unicorn",
      "phoenix",
      "griffin",
      "pegasus",
      "chimera",
      "basilisk",
      "kraken",
      "mermaid",
      "minotaur",
      "centaur",
      "faun",
      "hippogriff",
      "hydra",
      "cyclops",
      "yeti",
      "sasquatch",
      "bigfoot",
      "lycanthrope",
      "werewolf",
      "vampire",
      "zombie",
      "ghost",
      "goblin",
      "elf",
      "orc",
      "gnome",
      "troll",
      "fairy",
      "witch",
      "wizard",
      "brontosaurus",
      "sphinx",
      "leviathan",
      "naga",
      "salamander",
      "griffon",
      "basilisk",
      "kobold",
      "gremlin",
      "qilin",
      "kitsune",
      "tanuki",
      "drake",
      "wyvern",
      "hippogriff",
      "red wyvern",
      "manticore",
      "roc"
    ],
    "fantasy_tales": [
      "cinderella",
      "snow white",
      "little red riding hood",
      "pinocchio",
      "peter pan",
      "aladdin",
      "beauty and the beast",
      "the little mermaid",
      "rapunzel",
      "frozen",
      "mulan",
      "hercules",
      "the lion king",
      "the hunchback",
      "sleeping beauty",
      "hansel and gretel",
      "puss in boots",
      "the ugly duckling",
      "three little pigs",
      "the magic flute",
      "jack and the beanstalk",
      "alice",
      "oz",
      "the wizard of oz",
      "the little prince",
      "momo",
      "the neverending story",
      "the grump",
      "narnia",
      "the magic forest",
      "the gingerbread house",
      "the golden compass",
      "howl's moving castle",
      "spirited away",
      "my neighbor totoro",
      "magic pony",
      "dragons",
      "fairies",
      "gnomes",
      "goblins",
      "wizards",
      "witches",
      "castles",
      "princesses",
      "knights",
      "forests",
      "the pied piper",
      "tom thumb",
      "goldilocks"
    ],
    "school_things": [
      "backpack",
      "pencil case",
      "pencil",
      "pen",
      "eraser",
      "sharpener",
      "ruler",
      "notebook",
      "book",
      "blackboard",
      "chalk",
      "marker",
      "highlighter",
      "folder",
      "glue",
      "scissors",
      "paint",
      "watercolor",
      "rolling backpack",
      "planner",
      "homework",
      "exam",
      "recess",
      "playground",
      "cafeteria",
      "uniform",
      "smock",
      "desk",
      "chair",
      "classroom",
      "teacher",
      "principal",
      "library",
      "laboratory",
      "gym",
      "field",
      "goals",
      "ball",
      "snack",
      "canteen",
      "dismissal",
      "field trip",
      "camp",
      "map",
      "globe",
      "play dough",
      "paper",
      "cardboard",
      "compass",
      "calculator"
    ],
    "candies": [
      "gum",
      "lollipop",
      "candies",
      "licorice",
      "gummies",
      "gummy bears",
      "sweets",
      "chocolate",
      "bonbons",
      "marshmallow",
      "popsicle",
      "taffy",
      "jellybean",
      "gummy bears",
      "gummy worms",
      "cola gummies",
      "hard candy",
      "soft candy",
      "chewy candy",
      "toffee",
      "turron",
      "marzipan",
      "polvoron",
      "confetti",
      "lacasitos",
      "m and m",
      "kitkat",
      "oreo",
      "kinder",
      "huesitos",
      "sugus",
      "palotes",
      "sugar brick",
      "cloud",
      "pink cloud",
      "white cloud",
      "mint candies",
      "mint gum",
      "strawberry gum",
      "strawberry candy",
      "lemon candy",
      "heart lollipop",
      "chupachups",
      "alfajor",
      "coffee candy",
      "extra mint candy",
      "white chocolate",
      "dark chocolate",
      "sour candy"
    ],
    "toys": [
      "ball",
      "doll",
      "action figure",
      "stuffed animal",
      "car",
      "train",
      "boat",
      "airplane",
      "robot",
      "dinosaur",
      "lego",
      "blocks",
      "puzzle",
      "jigsaw puzzle",
      "marbles",
      "spinning top",
      "yoyo",
      "yo-yo",
      "play dough",
      "slinky",
      "roller skates",
      "bike",
      "scooter",
      "kite",
      "kitchen set",
      "doctor set",
      "tool set",
      "magic box",
      "cards",
      "domino",
      "chess",
      "checkers",
      "monopoly",
      "jenga",
      "game of goose",
      "parcheesi",
      "water launcher",
      "water gun",
      "fishing game",
      "memory game",
      "train track",
      "car track",
      "rc plane",
      "drone",
      "action figure",
      "rubik's cube",
      "slot car racing",
      "hula hoop",
      "light-up yoyo",
      "laser gun"
    ],
    "cartoons": [
      "mickey",
      "minnie",
      "donald",
      "goofy",
      "pluto",
      "tom and jerry",
      "spongebob",
      "patrick",
      "squidward",
      "dora",
      "boots",
      "diego",
      "peppa pig",
      "george",
      "bluey",
      "bingo",
      "paw patrol",
      "chase",
      "marshall",
      "skye",
      "rocky",
      "rubble",
      "blaze",
      "pj masks",
      "catboy",
      "owlette",
      "gekko",
      "pepa",
      "gumball",
      "darwin",
      "clarence",
      "scooby doo",
      "shaggy",
      "the simpsons",
      "homer",
      "marge",
      "bart",
      "lisa",
      "maggie",
      "futurama",
      "bender",
      "rick and morty",
      "morty",
      "gravity falls",
      "dipper",
      "mabel",
      "phineas",
      "ferb",
      "pokemon",
      "pikachu"
    ]
  }
}
